#!/usr/bin/env node
/**
 * Reads data/meryl_streep_complete.json and generates src/quotes.ts
 * with all 1,174 quotes from all 11 collections.
 *
 * Usage: node scripts/build-quotes.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const INPUT = join(ROOT, 'data', 'meryl_streep_complete.json');
const OUTPUT = join(ROOT, 'src', 'quotes.ts');

/** Strip surrounding curly/straight quotes from quote text. */
function stripOuterQuotes(s) {
  if (!s) return '';
  return s.replace(/^[\s"\u201c\u201d'\u2018\u2019]+|[\s"\u201c\u201d'\u2018\u2019]+$/g, '').trim();
}

/** Escape a string for TypeScript double-quoted literal. */
function escapeString(s) {
  if (s == null) return '';
  return String(s)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r/g, '')
    .replace(/\n/g, '\\n')
    .replace(/\t/g, '\\t');
}

/** Normalize a single entry into the Quote shape. */
function normalizeEntry(collection, entry, index) {
  const id = `${collection}-${index + 1}`;

  let quote = '';
  let streepified = '';
  let attribution = '';
  let source = '';
  let category = entry['Category'] || '';

  switch (collection) {
    case 'peril_to_meryl':
      quote = stripOuterQuotes(entry['Quote']);
      streepified = stripOuterQuotes(entry['Merylified Version'] || entry['Streepified Version'] || entry['Quote']);
      attribution = entry['Attribution'] || '';
      source = entry['Source / Context'] || '';
      break;

    case 'words_of_streep':
      quote = stripOuterQuotes(entry['Quote']);
      streepified = quote;
      attribution = 'Meryl Streep';
      source = entry['Source / Context'] || '';
      break;

    case 'about_meryl_streep':
      quote = stripOuterQuotes(entry['Quote']);
      streepified = quote;
      attribution = entry['Who Said It'] || 'Unknown';
      source = entry['Context'] || '';
      break;

    case 'speeches_and_characters':
      quote = stripOuterQuotes(entry['Quote / Moment'] || entry['Quote']);
      streepified = quote;
      attribution = 'Meryl Streep';
      source = entry['Context'] || '';
      break;

    default:
      // street_to_streep, steep_to_streep, sleep_to_streep, deep_to_streep,
      // sweep_to_streep, streak_to_streep, creep_to_streep
      quote = stripOuterQuotes(entry['Quote']);
      streepified = stripOuterQuotes(entry['Streepified Version'] || entry['Quote']);
      attribution = entry['Attribution'] || 'Unknown';
      source = entry['Source / Context'] || '';
      break;
  }

  return { id, quote, streepified, attribution, source, category, collection };
}

/** Load the exclusion list (long_lost_lore.json) */
function loadExclusions() {
  const lorePath = join(ROOT, 'data', 'long_lost_lore.json');
  try {
    const lore = JSON.parse(readFileSync(lorePath, 'utf8'));
    return new Set(lore.entries.map(e => e.id));
  } catch {
    return new Set();
  }
}

function formatEntry(q) {
  return `  { id: "${q.id}", quote: "${escapeString(q.quote)}", streepified: "${escapeString(q.streepified)}", attribution: "${escapeString(q.attribution)}", source: "${escapeString(q.source)}", category: "${escapeString(q.category)}", collection: "${q.collection}" },`;
}

function main() {
  const raw = readFileSync(INPUT, 'utf8');
  const data = JSON.parse(raw);
  const excluded = loadExclusions();

  const all = [];
  const collectionOrder = [
    'street_to_streep',
    'steep_to_streep',
    'sleep_to_streep',
    'deep_to_streep',
    'sweep_to_streep',
    'peril_to_meryl',
    'streak_to_streep',
    'creep_to_streep',
    'words_of_streep',
    'about_meryl_streep',
    'speeches_and_characters',
  ];

  const lines = [];
  lines.push('// ═══════════════════════════════════════════');
  lines.push('// AUTO-GENERATED by scripts/build-quotes.mjs');
  lines.push('// DO NOT EDIT BY HAND — run `npm run build-quotes` to regenerate');
  lines.push('// ═══════════════════════════════════════════');
  lines.push('');
  lines.push('export interface Quote {');
  lines.push('  id: string;');
  lines.push('  quote: string;');
  lines.push('  streepified: string;');
  lines.push('  attribution: string;');
  lines.push('  source: string;');
  lines.push('  category: string;');
  lines.push('  collection: string;');
  lines.push('  // V2 optional fields (populated by build-walken-quotes.mjs)');
  lines.push('  memeScore?: number;');
  lines.push('  walkenReading?: string;');
  lines.push('}');
  lines.push('');
  lines.push('export const QUOTES: Quote[] = [');

  let totalCount = 0;
  let excludedCount = 0;
  for (const name of collectionOrder) {
    const coll = data.collections[name];
    if (!coll || !coll.entries) {
      console.warn(`[build-quotes] Missing collection: ${name}`);
      continue;
    }
    lines.push('');
    lines.push(`  // ── ${name} ──`);
    for (let i = 0; i < coll.entries.length; i++) {
      const normalized = normalizeEntry(name, coll.entries[i], i);
      // Skip quotes in the long_lost_lore exclusion list
      if (excluded.has(normalized.id)) {
        excludedCount++;
        continue;
      }
      all.push(normalized);
      lines.push(formatEntry(normalized));
      totalCount++;
    }
  }

  lines.push('];');
  lines.push('');
  lines.push('// Collections where the quote is legitimately "from" or "about" Streep,');
  lines.push('// so the quote and streepified fields being identical is correct.');
  lines.push('const DIRECT_STREEP_COLLECTIONS = new Set([');
  lines.push("  'words_of_streep',");
  lines.push("  'about_meryl_streep',");
  lines.push("  'speeches_and_characters',");
  lines.push(']);');
  lines.push('');
  lines.push('const STREEP_WORD = /\\b(Streep\\w*|Meryl\\w*)\\b/i;');
  lines.push('');
  lines.push('/**');
  lines.push(' * A quote is "valid" if either:');
  lines.push(" *   - it's from a direct Streep collection (quote is about/by her)");
  lines.push(' *   - OR its streepified text contains a Streep/Meryl pun word');
  lines.push(' * This filters out entries where the streepified version was never authored.');
  lines.push(' */');
  lines.push('const VALID_QUOTES = QUOTES.filter((q) => {');
  lines.push('  if (DIRECT_STREEP_COLLECTIONS.has(q.collection)) return true;');
  lines.push('  return STREEP_WORD.test(q.streepified);');
  lines.push('});');
  lines.push('');
  lines.push('let lastQuoteIndex = -1;');
  lines.push('');
  lines.push('export function getRandomQuote(): Quote {');
  lines.push('  const pool = VALID_QUOTES.length > 0 ? VALID_QUOTES : QUOTES;');
  lines.push('  let index: number;');
  lines.push('  do {');
  lines.push('    index = Math.floor(Math.random() * pool.length);');
  lines.push('  } while (index === lastQuoteIndex && pool.length > 1);');
  lines.push('  lastQuoteIndex = index;');
  lines.push('  return pool[index];');
  lines.push('}');
  lines.push('');

  writeFileSync(OUTPUT, lines.join('\n'), 'utf8');

  const validCount = all.filter((q) => {
    const direct = ['words_of_streep', 'about_meryl_streep', 'speeches_and_characters'];
    if (direct.includes(q.collection)) return true;
    return /\b(Streep\w*|Meryl\w*)\b/i.test(q.streepified);
  }).length;

  console.log(`[build-quotes] Wrote ${OUTPUT}`);
  console.log(`[build-quotes] Total in file: ${totalCount}`);
  console.log(`[build-quotes] Excluded (long_lost_lore): ${excludedCount}`);
  console.log(`[build-quotes] Valid (showable) quotes: ${validCount}`);
  console.log(`[build-quotes] Filtered at runtime (no pun word): ${totalCount - validCount}`);
}

main();
